apiVersion: apps/v1
kind: Deployment
metadata:
 name: the-deployment
 namespace: the-namespace
 labels:
   deployment: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: demo
    spec:
      containers:
      - name: the-container
        image: hseligson/kustomize-sample-app:v1.0.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources: {}
status: {}
        env:
        - name: MY_MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: mysqlDB
