apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s.nsfolk.info
  - http:
      paths:
        backend:
          service:
            name: demo
            port:
              number: 8080